### Reading list CRUD requests

@baseUrl = http://localhost:8080
@basicAuth = YWRtaW46YWRtaW4=

### Get CSRF token
GET {{baseUrl}}/api/books
Authorization: Basic {{basicAuth}}

> {% client.global.set("csrfToken", response.cookies.valueOf("XSRF-TOKEN")); %}

### Create a book
# @name createBook
POST {{baseUrl}}/api/books
Content-Type: application/json
Authorization: Basic {{basicAuth}}
X-XSRF-TOKEN: {{csrfToken}}

{
  "title": "The Left Hand of Darkness",
  "author": "Ursula K. Le Guin",
  "status": "TO_READ"
}

> {% client.global.set("bookId", response.body.id); %}

### Read all books
GET {{baseUrl}}/api/books
Authorization: Basic {{basicAuth}}

### Read one book
GET {{baseUrl}}/api/books/{{bookId}}
Authorization: Basic {{basicAuth}}

### Update the book
PUT {{baseUrl}}/api/books/{{bookId}}
Content-Type: application/json
Authorization: Basic {{basicAuth}}
X-XSRF-TOKEN: {{csrfToken}}

{
  "title": "The Left Hand of Darkness",
  "author": "Ursula K. Le Guin",
  "status": "READING"
}

### Delete the book
DELETE {{baseUrl}}/api/books/{{bookId}}
Authorization: Basic {{basicAuth}}
X-XSRF-TOKEN: {{csrfToken}}
