@baseUrl = http://localhost:8080
@bookId = 1
@basicAuth = YWRtaW46YWRtaW4=

### GET CSRF TOKEN
# Run this request before POST, PUT, or DELETE.
# The response stores the XSRF-TOKEN cookie for the following requests.
# @name getCsrfToken
GET {{baseUrl}}/api/csrf-token
Authorization: Basic {{basicAuth}}

> {% client.global.set("csrfToken", response.body.token); %}

###

### GET ALL BOOKS
GET {{baseUrl}}/api/books
Authorization: Basic {{basicAuth}}



### GET ONE BOOK
GET {{baseUrl}}/api/books/{{bookId}}
Authorization: Basic {{basicAuth}}



### DELETE ONE BOOK
DELETE {{baseUrl}}/api/books/{{bookId}}
Authorization: Basic {{basicAuth}}
X-XSRF-TOKEN: {{csrfToken}}



### CREATE ONE BOOK
POST {{baseUrl}}/api/books
Content-Type: application/json
Authorization: Basic {{basicAuth}}
X-XSRF-TOKEN: {{csrfToken}}

{
  "title": "The Left Hand of Darkness",
  "author": "Ursula K. Le Guin",
  "status": "TO_READ"
}

> {% client.global.set("bookId", response.body.id); %}



### UPDATE ONE BOOK
PUT {{baseUrl}}/api/books/{{bookId}}
Content-Type: application/json
Authorization: Basic {{basicAuth}}
X-XSRF-TOKEN: {{csrfToken}}

{
  "title": "The Left Hand of Darkness",
  "author": "Ursula K. Le Guin",
  "status": "READING"
}
