spring.application.name=demo
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/reading_list}
spring.datasource.username=${DB_USERNAME:reading_list}
spring.datasource.password=${DB_PASSWORD:reading_list}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# AUTH
spring.security.user.name=user
spring.security.user.password=password
spring.security.user.roles=USER